### ISSUE TITLE
Add an explanation that this is not recommended and defeats the purpose of act()

### ISSUE THREAD

**Issue by gaearon** [webNeat/react-act#1]
See my response in 
https://github.com/facebook/react/issues/15000#issuecomment-468990663

I understand if you prefer to mute the warning until there is an idiomatic fix for async code but we need to be clear to anyone using this library that it makes the issue worse and isn’t a “best practice”.

**Comment by webNeat** [comment]
Thanks @gaearon for opening this issue. I added a note to README.
